/**
 * 全局事件定义
 */
//事件
var GameEvent = {
    SHOW_LOADINGVIEW: "show_loadingview",
};
//模块事件
var PanelNotify = {
    SHOW_LOADING: "SHOW_LOADING",
    HIDE_LOADING: "HIDE_LOADING",
    LOGIN_OPEN_LOGIN: "LOGIN_OPEN_LOGIN",
    LOGIN_CLOSE_LOGIN: "LOGIN_CLOSE_LOGIN",
    LOGIN_UPDATE_REGIST: "LOGIN_UPDATE_REGIST",
    LOGIN_UPDATE_LOGIN: "LOGIN_UPDATE_LOGIN",
    LOGIN_SERVER_SELECT: "LOGIN_SERVER_SELECT",
    LOGIN_UPDATE_SERVER: "LOGIN_UPDATE_SERVER",
    LOGIN_OPEN_MAKE_ROLE: "LOGIN_OPEN_MAKE_ROLE",
    LOGIN_CLOSE_MAKE_ROLE: "LOGIN_CLOSE_MAKE_ROLE",
    // player
    PLAYER_UPDATE_PLAYER_INFO_REQ: "PLAYER_UPDATE_PLAYER_INFO_REQ",
    PLAYER_UPDATE_PLAYER_INFO_RESP: "PLAYER_UPDATE_PLAYER_INFO_RESP",
    PLAYER_UPDATE_PLAYER_INFO: "PLAYER_UPDATE_PLAYER_INFO",
    PLAYER_OFFLINE_INFO: "PLAYER_OFFLINE_INFO",
    PLAYER_FASTFIGHT_INFO: "PLAYER_FASTFIGHT_INFO",
    PLAYER_FASTFIGHT_RESULT: "PLAYER_FASTFIGHT_RESULT",
    // ======== Hero ==========
    HERO_ON_HERO_SELECT: "HERO_ON_HERO_SELECT",
    HERO_ON_HERO_UPDATE_VIEW: "HERO_ON_HERO_UPDATE_VIEW",
    HERO_NEW_PARTNER: "HERO_NEW_PARTNER",
    HERO_ACTIVE_SPECIAL: "HERO_ACTIVE_SPECIAL",
    HERO_CHANGE: "HERO_CHANGE",
    //技能
    HERO_OPEN_SKILL_PANEL: "HERO_OPEN_SKILL_PANEL",
    HERO_CLOSE_SKILL_PANEL: "HERO_CLOSE_SKILL_PANEL",
    HERO_UPDATE_SKILL_PANEL: "HERO_UPDATE_SKILL_PANEL",
    // 背包
    HERO_OPEN_BAG: "HERO_OPEN_BAG",
    HERO_CLOSE_BAG: "HERO_CLOSE_BAG",
    HERO_ON_HERO_BAG_UPDATE: "HERO_ON_HERO_BAG_UPDATE",
    HERO_BAG_NOT_ENOUGH: "HERO_BAG_NOT_ENOUGH",
    HERO_MONEY_NOT_ENOUGH: "HERO_MONEY_NOT_ENOUGH",
    HERO_COIN_NOT_ENOUGH: "HERO_COIN_NOT_ENOUGH",
    HERO_ITEMINFO_UPDATE: "HERO_ITEMINFO_UPDATE",
    //装备
    HERO_TAP_EQUIP: "HERO_TAP_EQUIP",
    HERO_UPDATE_EQUIP: "HERO_UPDATE_EQUIP",
    HERO_CLOSE_EQUIP_SELECT: "HERO_CLOSE_EQUIP_SELECT",
    HERO_SPECIAL_EQUIP_UPDATE: "HERO_SPECIAL_EQUIP_UPDATE",
    // ======== Hero End ==========
    //熔炼
    SMELT_SMELT_EQUIP: "SMELT_SMELT_EQUIP",
    SMELT_ORANGE_EQUIP: "ORANGE_SMELT_EQUIP",
    //锻造
    FORGE_STRENGTH_EQUIP: "FORGE_STRENGTH_EQUIP",
    FORGE_STAR_EQUIP: "FORGE_STAR_EQUIP",
    FORGE_ORANGE_EQUIP: "FORGE_ORANGE_EQUIP",
    //商城
    SHOP_UPDATE_LIST: "SHOP_UPDATE_LIST",
    SHOP_BUY_WIN: "SHOP_BUY_WIN",
    SHOP_CLOSE_BUY_WIN: "SHOP_CLOSE_BUY_WIN",
    //登录
    LOGIN_UPDATE_SERVER_LIST: "LOGIN_UPDATE_SERVER_LIST",
    LOGIN_NOTICE_LIST: "LOGIN_NOTICE_LIST",
    //广播
    // BROADCAST_PLAY: "BROADCAST_PLAY",
    //宝石
    JEWEL_UPDATE_VIEW: "JEWEL_UPDATE_VIEW",
    JEWEL_UPDATE_ALL_VIEW: "JEWEL_UPDATE_ALL_VIEW",
    //boss
    BOSS_OPEN: "BOSS_OPEN",
    BOSS_CHALLENGE: "BOSS_CHALLENGE",
    SHOW_BOSS_RESULT: "SHOW_BOSS_RESULT",
    BOSS_WAVE_UPDATE: "BOSS_WAVE_UPDATE",
    BOSS_REWARD_UPDATE: "BOSS_REWARD_UPDATE",
    BOSS_MEET: "BOSS_MEET",
    BOSS_MEET_START_CHALLENGE: "BOSS_MEET_START_CHALLENGE",
    //main
    MAIN_CLOSE_BUTTON: "MAIN_CLOSE_BUTTON",
    MAIN_OPEN_BUTTON: "MAIN_OPEN_BUTTON",
    MAIN_BOSSICON_EFFECT_OPEN: "MAIN_BOSSICON_EFFECT_OPEN",
    MAIN_BOSSICON_EFFECT_CLOSE: "MAIN_BOSSICON_EFFECT_CLOSE",
    MAIN_BOSS_CAN_CHANLLENGE: "MAIN_BOSS_CAN_CHANLLENGE",
    MAIN_BOSS_NOT_CHANLLENGE: "MAIN_BOSS_NOT_CHANLLENGE",
    MAIN_LINE_TASK_GET_INFO: "MAIN_LINE_TASK_GET_INFO",
    MAIN_HIDE_FIGHT_INFO: "MAIN_HIDE_FIGHT_INFO",
    MAIN_BACKPAG_FULL_TIPS: "MAIN_BACKPAG_FULL_TIPS",
    REMOVE_TOP_BTN: "REMOVE_TOP_BTN",
    ADD_TOP_BTN: "ADD_TOP_BTN",
    //wing
    WING_INFO_UPDATE: "WING_INFO_UPDATE",
    WING_EQUIP_TIP: "WING_EQUIP_TIP",
    WING_TRANSFORM_RESULT: "WING_TRANSFORM_RESULT",
    WING_STEP_SUCCESS: "WING_STEP_SUCCESS",
    WING_EQUIP_STEP_SUCCESS: "WING_EQUIP_STEP_SUCCESS",
    //chat
    CHAT_HAS_NEW_INFO: "CHAT_HAS_NEW_INFO",
    CHAT_LIST_UPDATE: "CHAT_LIST_UPDATE",
    //mail
    MAIL_INFO_UPDATE: "MAIL_INFO_UPDATE",
    MAIL_ATTACHMENT_SUCCESS: "MAIL_ATTACHMENT_SUCCESS",
    //sign
    SIGN_INFO_UPDATE: "SIGN_INFO_UPDATE",
    SIGN_DAYS_CHANGE: "SIGN_DAYS_CHANGE",
    RESIGN_DAYS_CHANGE: "RESIGN_DAYS_CHANGE",
    SIGN_REWARD_UPDATE: "SIGN_REWARD_UPDATE",
    //合成
    SYNTHESIS_VIEW: "SYNTHESIS_VIEW",
    SYNTHESIS_JEWEL_VIEW: "SYNTHESIS_JEWEL_VIEW",
    SYNTHESIS_WING_VIEW: "SYNTHESIS_WING_VIEW",
    SYNTHESIS_EQUIP_VIEW: "SYNTHESIS_EQUIP_VIEW",
    SYNTHESIS_ALL_VIEW: "SYNTHESIS_ALL_VIEW",
    //转生
    REBORN_UPDATE_VIEW: "REBORN_UPDATE_VIEW",
    REBORN_SUCCESS: "REBORN_SUCCESS",
    REBORN_UPDATE_INFO_VIEW: "REBORN_UPDATE_INFO_VIEW",
    //每日必做
    MUSTDO_UPDATEACTIVITY: "MUSTDO_UPDATEACTIVITY",
    MUSTDO_UPDATEMEDAL: "MUSTDO_UPDATEMEDAL",
    MUSTDO_UPDATESACHIEVE: "MUSTDO_UPDATESACHIEVE",
    MUSTDO_UPDATETITLE: "MUSTDO_UPDATETITLE",
    //福利
    WELFARE_UPDATELEVELLIST: "WELFARE_UPDATELEVELLIST",
    //寻宝
    RAIDER_UPDATE_VIEW: "RAIDER_UPDATE_VIEW",
    RAIDER_UPDATE_BROADCAST: "RAIDER_UPDATE_BROADCAST",
    RAIDER_UPDATE_STORAGE: "RAIDER_UPDATE_STORAGE",
    RAIDER_OPEN_REWARD: "RAIDER_OPEN_REWARD",
    //神器
    ARTIFACT_UPDATE_VIEW: "ARTIFACT_UPDATE_VIEW",
    ARTIFACT_UPGRADE_BACK: "ARTIFACT_UPGRADE_BACK",
    //活动
    ACTIVITY_OPEN_MAIN: "ACTIVITY_OPEN_MAIN",
    ACTIVITY_UPDATE_MAIN_VIEW: "ACTIVITY_UPDATE_MAIN_VIEW",
    ACTIVITY_UPDATE_VIEW: "ACTIVITY_UPDATE_VIEW",
    ACTIVITY_CHANGE_VIEW: "ACTIVITY_CHANGE_VIEW",
    //vip
    VIP_REWARD_UPDATE: "VIP_REWARD_UPDATE",
    VIP_GET_REWARD_SUCCESS: "VIP_GET_REWARD_SUCCESS",
    //pageView
    PAGE_CURRENTINDEX_UPDATE: "PAGE_CURRENTINDEX_UPDATE",
    //monthCard
    MONTHCARD_INFO_UPDATE: "MONTHCARD_INFO_UPDATE",
    MONTHCARD_GET_SUCCESS: "MONTHCARD_GET_SUCCESS",
    //排行榜更新
    RANK_INFO_UPDATE: "RANK_INFO_UPDATE",
    RANK_WORSHIP_UPDATE: "RANK_WORSHIP_UPDATE",
    RANK_INFO_NOTHING: "RANK_INFO_NOTHING",
    //关卡榜
    RANK_GUANQIA_UPDATE: "RANK_GUANQIA_UPDATE",
    //副本
    COPY_INFO_UPDATE: "COPY_INFO_UPDATE",
    COPY_ASK_CHALLENGE_RESULT: "COPY_ASK_CHALLENGE_RESULT",
    //投资
    INVEST_INFO_UPDATE: "INVEST_INFO_UPDATE",
    //充值
    RECHARGE_INFO_UPDATE: "RECHARGE_INFO_UPDATE",
    //转盘
    FORTUNE_VIEW_INFO_UPDATE: "FORTUNE_VIEW_INFO_UPDATE",
    FORTUNE_POOL_INFO_UPDATE: "FORTUNE_POOL_INFO_UPDATE",
    FORTUNE_WHEEL_START: "FORTUNE_WHEEL_START",
    FORTUNE_WHEEL_STOP: "FORTUNE_WHEEL_STOP",
    //争霸
    HEGEMONY_INFO_UPDATE: "HEGEMONY_INFO_UPDATE",
    HEGEMONY_MATCH_UPDATE: "HEGEMONY_MATCH_UPDATE",
    HEGEMONY_REWARD_UPDATE: "HEGEMONY_REWARD_UPDATE",
    //世界boss
    WORLDBOSS_INFO_UPDATE: "WORLDBOSS_INFO_UPDATE",
    WORLDBOSS_KILLRECORD_UPDATE: "WORLDBOSS_KILLRECORD_UPDATE",
    WORLDBOSS_FIGHT: "WORLDBOSS_FIGHT",
    WORLDBOSS_CHEER: "WORLDBOSS_CHEER",
    WORLDBOSS_CHEER_RESULT: "WORLDBOSS_CHEER_RESULT",
    WORLDBOSS_HURT_RANK_UPDATE: "WORLDBOSS_HURT_RANK_UPDATE",
    //遭遇战
    ENCOUNTER_INFO_UPDATE: "ENCOUNTER_INFO_UPDATE",
    ENCOUNTER_PK_REDUCE_SUCCESS: "ENCOUNTER_PK_REDUCE_SUCCESS",
    ENCOUNTER_START_CHALLENGE_SUCCESS: "ENCOUNTER_START_CHALLENGE_SUCCESS",
    //遭遇战
    ENCOUNTER_LOG_UPDATE: "ENCOUNTER_LOG_UPDATE",
    //玩家战力变化
    PLAYER_COMBAT_UPDATE: "PLAYER_COMBAT_UPDATE",
    //查看玩家信息
    PLAYER_MSG_INQUIRE: "PLAYER_MSG_INQUIRE",
    PLAYER_HERO_ATTRIBUTE_INDEX_CHANGE: "PLAYER_HERO_ATTRIBUTE_INDEX_CHANGE",
    //战斗力显示飘字属性播放完成
    COMBAT_ATTR_FINISH: "COMBAT_ATTR_FINISH",
    //战斗力提升战斗力播放完成
    COMBAT_INCREASE_FINISH: "COMBAT_INCREASE_FINISH",
};
//# sourceMappingURL=GlobalEvent.js.map