/**
 * 全局事件定义
 */

//事件
const GameEvent = {
    SHOW_LOADINGVIEW: "show_loadingview",//显示场景加载页面
}

//模块事件
const PanelNotify = {
    SHOW_LOADING: "SHOW_LOADING",
    HIDE_LOADING: "HIDE_LOADING",
    LOGIN_OPEN_LOGIN: "LOGIN_OPEN_LOGIN",
    LOGIN_CLOSE_LOGIN: "LOGIN_CLOSE_LOGIN",
    LOGIN_UPDATE_REGIST: "LOGIN_UPDATE_REGIST",
    LOGIN_UPDATE_LOGIN: "LOGIN_UPDATE_LOGIN",
    LOGIN_SERVER_SELECT: "LOGIN_SERVER_SELECT",
    LOGIN_UPDATE_SERVER: "LOGIN_UPDATE_SERVER",
    LOGIN_OPEN_MAKE_ROLE: "LOGIN_OPEN_MAKE_ROLE",
    LOGIN_CLOSE_MAKE_ROLE: "LOGIN_CLOSE_MAKE_ROLE",

    // player
    PLAYER_UPDATE_PLAYER_INFO_REQ: "PLAYER_UPDATE_PLAYER_INFO_REQ",          //刷新玩家数据请求
    PLAYER_UPDATE_PLAYER_INFO_RESP: "PLAYER_UPDATE_PLAYER_INFO_RESP",          //刷新玩家数据服务器返回
    PLAYER_UPDATE_PLAYER_INFO: "PLAYER_UPDATE_PLAYER_INFO",          //刷新玩家数据（包括战斗力变化了也会发送该事件）
    PLAYER_OFFLINE_INFO: "PLAYER_OFFLINE_INFO",    //离线战斗数据
    PLAYER_FASTFIGHT_INFO: "PLAYER_FASTFIGHT_INFO",    //快速战斗数据
    PLAYER_FASTFIGHT_RESULT: "PLAYER_FASTFIGHT_RESULT",    //快速战斗结果

    // ======== Hero ==========
    HERO_ON_HERO_SELECT: "HERO_ON_HERO_SELECT",//选择英雄
    HERO_ON_HERO_UPDATE_VIEW: "HERO_ON_HERO_UPDATE_VIEW",//更新英雄界面
    HERO_NEW_PARTNER: "HERO_NEW_PARTNER",//选择新英雄
    HERO_ACTIVE_SPECIAL: "HERO_ACTIVE_SPECIAL",//激活特殊装备
    HERO_CHANGE: "HERO_CHANGE",  //切换英雄


    //技能
    HERO_OPEN_SKILL_PANEL: "HERO_OPEN_SKILL_PANEL",
    HERO_CLOSE_SKILL_PANEL: "HERO_CLOSE_SKILL_PANEL",
    HERO_UPDATE_SKILL_PANEL: "HERO_UPDATE_SKILL_PANEL",

    // 背包
    HERO_OPEN_BAG: "HERO_OPEN_BAG",
    HERO_CLOSE_BAG: "HERO_CLOSE_BAG",
    HERO_ON_HERO_BAG_UPDATE: "HERO_ON_HERO_BAG_UPDATE",              //英雄背包数据更新
    HERO_BAG_NOT_ENOUGH: "HERO_BAG_NOT_ENOUGH",                      //背包不足
    HERO_MONEY_NOT_ENOUGH: "HERO_MONEY_NOT_ENOUGH",                      //元宝不足
    HERO_COIN_NOT_ENOUGH: "HERO_COIN_NOT_ENOUGH",                      //金币不足
    HERO_ITEMINFO_UPDATE : "HERO_ITEMINFO_UPDATE",  //道具信息更新

    //装备
    HERO_TAP_EQUIP: "HERO_TAP_EQUIP", //点击了某个装备位置
    HERO_UPDATE_EQUIP: "HERO_UPDATE_EQUIP", //更新装备面板数据
    HERO_CLOSE_EQUIP_SELECT: "HERO_CLOSE_EQUIP_SELECT", //关闭装备选择

    HERO_SPECIAL_EQUIP_UPDATE: "HERO_SPECIAL_EQUIP_UPDATE", //特殊装备更新
    // ======== Hero End ==========

    //熔炼
    SMELT_SMELT_EQUIP: "SMELT_SMELT_EQUIP", //熔炼装备
    SMELT_ORANGE_EQUIP: "ORANGE_SMELT_EQUIP", //熔炼橙色装备

    //锻造
    FORGE_STRENGTH_EQUIP: "FORGE_STRENGTH_EQUIP", //强化装备
    FORGE_STAR_EQUIP: "FORGE_STAR_EQUIP", //升星装备
    FORGE_ORANGE_EQUIP: "FORGE_ORANGE_EQUIP", //橙色装备强化

    //商城
    SHOP_UPDATE_LIST: "SHOP_UPDATE_LIST", //更新商城数据
    SHOP_BUY_WIN: "SHOP_BUY_WIN", //打开商城数量选择
    SHOP_CLOSE_BUY_WIN: "SHOP_CLOSE_BUY_WIN", //关闭商城数量选择

    //登录
    LOGIN_UPDATE_SERVER_LIST: "LOGIN_UPDATE_SERVER_LIST",//更新服务器列表
    LOGIN_NOTICE_LIST: "LOGIN_NOTICE_LIST",//获取了游戏公告的数据
    //广播
    // BROADCAST_PLAY: "BROADCAST_PLAY",

    //宝石
    JEWEL_UPDATE_VIEW: "JEWEL_UPDATE_VIEW", //宝石升级
    JEWEL_UPDATE_ALL_VIEW: "JEWEL_UPDATE_ALL_VIEW", //宝石一键镶嵌

    //boss
    BOSS_OPEN: "BOSS_OPEN", //打开挑战boss信息页面
    BOSS_CHALLENGE: "BOSS_CHALLENGE",  //挑战boss
    SHOW_BOSS_RESULT: "SHOW_BOSS_RESULT",  //挑战boss结果
    BOSS_WAVE_UPDATE: "BOSS_WAVE_UPDATE",   //小怪波数更新
    BOSS_REWARD_UPDATE: "BOSS_REWARD_UPDATE",  //boss通关奖励更新
    BOSS_MEET: "BOSS_MEET",   //随机遭遇了boss
    BOSS_MEET_START_CHALLENGE: "BOSS_MEET_START_CHALLENGE", //请求挑战随机遭遇boss成功

    //main
    MAIN_CLOSE_BUTTON: "MAIN_CLOSE_BUTTON",  //挑战boss时关闭上面和侧面图标
    MAIN_OPEN_BUTTON: "MAIN_OPEN_BUTTON",  //挑战boss完毕打开上面和侧面图标
    MAIN_BOSSICON_EFFECT_OPEN: "MAIN_BOSSICON_EFFECT_OPEN", //达到波数条件打开boss图标特效
    MAIN_BOSSICON_EFFECT_CLOSE: "MAIN_BOSSICON_EFFECT_CLOSE", //挑战boss完毕关闭boss图标特效
    MAIN_BOSS_CAN_CHANLLENGE: "MAIN_BOSS_CAN_CHANLLENGE", //可以挑战boss
    MAIN_BOSS_NOT_CHANLLENGE: "MAIN_BOSS_NOT_CHANLLENGE", //不能挑战boss
    MAIN_LINE_TASK_GET_INFO:"MAIN_LINE_TASK_GET_INFO",//主线任务更新
    MAIN_HIDE_FIGHT_INFO: "MAIN_HIDE_FIGHT_INFO",  //隐藏主界面右上角场景信息

    MAIN_BACKPAG_FULL_TIPS:"MAIN_BACKPAG_FULL_TIPS",//背包已满提示信息

    REMOVE_TOP_BTN:"REMOVE_TOP_BTN",//移除顶部按钮
    ADD_TOP_BTN:"ADD_TOP_BTN",//添加顶部按钮

    //wing
    WING_INFO_UPDATE: "WING_INFO_UPDATE",  //winginfo更新
    WING_EQUIP_TIP: "WING_EQUIP_TIP",  //打开羽翼装备提示框
    WING_TRANSFORM_RESULT: "WING_TRANSFORM_RESULT", //羽翼装备转换结果
    WING_STEP_SUCCESS: "WING_STEP_SUCCESS",  //羽翼升阶成功
    WING_EQUIP_STEP_SUCCESS: "WING_EQUIP_STEP_SUCCESS",  //羽翼装备升阶成功    

    //chat
    CHAT_HAS_NEW_INFO: "CHAT_HAS_NEW_INFO",//收到一条新消息
    CHAT_LIST_UPDATE: "CHAT_LIST_UPDATE",//收到聊天信息数据

    //mail
    MAIL_INFO_UPDATE: "MAIL_INFO_UPDATE",//邮件信息变更（读、收、领取附件时触发）
    MAIL_ATTACHMENT_SUCCESS: "MAIL_ATTACHMENT_SUCCESS",

    //sign
    SIGN_INFO_UPDATE: "SIGN_INFO_UPDATE",//获取签到表信息
    SIGN_DAYS_CHANGE: "SIGN_DAYS_CHANGE",//签到成功
    RESIGN_DAYS_CHANGE: "RESIGN_DAYS_CHANGE",//补签成功
    SIGN_REWARD_UPDATE: "SIGN_REWARD_UPDATE",//领取签到额外奖励

    //合成
    SYNTHESIS_VIEW: "SYNTHESIS_VIEW", //合成成功
    SYNTHESIS_JEWEL_VIEW: "SYNTHESIS_JEWEL_VIEW", //合成宝石成功
    SYNTHESIS_WING_VIEW: "SYNTHESIS_WING_VIEW", //合成羽翼成功
    SYNTHESIS_EQUIP_VIEW: "SYNTHESIS_EQUIP_VIEW", //合成装备成功
    SYNTHESIS_ALL_VIEW: "SYNTHESIS_ALL_VIEW", //一键合成成功

    //转生
    REBORN_UPDATE_VIEW: "REBORN_UPDATE_VIEW", //转生主界面更新
    REBORN_SUCCESS: "REBORN_SUCCESS", //转生成功
    REBORN_UPDATE_INFO_VIEW: "REBORN_UPDATE_INFO_VIEW", //转生兑换更新


    //每日必做
    MUSTDO_UPDATEACTIVITY: "MUSTDO_UPDATEACTIVITY",//活跃任务更新
    MUSTDO_UPDATEMEDAL: "MUSTDO_UPDATEMEDAL",//勋章信息更新
    MUSTDO_UPDATESACHIEVE: "MUSTDO_UPDATESACHIEVE",//成就界面更新
    MUSTDO_UPDATETITLE:"MUSTDO_UPDATETITLE",//称号界面更新
    //福利
    WELFARE_UPDATELEVELLIST: "WELFARE_UPDATELEVELLIST",

    //寻宝
    RAIDER_UPDATE_VIEW: "RAIDER_UPDATE_VIEW",
    RAIDER_UPDATE_BROADCAST: "RAIDER_UPDATE_BROADCAST",
    RAIDER_UPDATE_STORAGE: "RAIDER_UPDATE_STORAGE",
    RAIDER_OPEN_REWARD: "RAIDER_OPEN_REWARD",

    //神器
    ARTIFACT_UPDATE_VIEW: "ARTIFACT_UPDATE_VIEW",
    ARTIFACT_UPGRADE_BACK: "ARTIFACT_UPGRADE_BACK",

    //活动
    ACTIVITY_OPEN_MAIN : "ACTIVITY_OPEN_MAIN",   //打开活动页面
    ACTIVITY_UPDATE_MAIN_VIEW : "ACTIVITY_UPDATE_MAIN_VIEW",  //更新活动主界面
    ACTIVITY_UPDATE_VIEW : "ACTIVITY_UPDATE_VIEW", //更新活动子页面
    ACTIVITY_CHANGE_VIEW : "ACTIVITY_CHANGE_VIEW", //改变活动子页面


    //vip
    VIP_REWARD_UPDATE: "VIP_REWARD_UPDATE",   //VIP奖励更新
    VIP_GET_REWARD_SUCCESS: "VIP_GET_REWARD_SUCCESS",  //VIP奖励获取成功

    //pageView
    PAGE_CURRENTINDEX_UPDATE: "PAGE_CURRENTINDEX_UPDATE",  //当前页面索引更新

    //monthCard
    MONTHCARD_INFO_UPDATE: "MONTHCARD_INFO_UPDATE",    //月卡数据更新
    MONTHCARD_GET_SUCCESS: "MONTHCARD_GET_SUCCESS",   //领取月卡奖励成功

    //排行榜更新
    RANK_INFO_UPDATE:"RANK_INFO_UPDATE",
    RANK_WORSHIP_UPDATE:"RANK_WORSHIP_UPDATE",//膜拜
    RANK_INFO_NOTHING:"RANK_INFO_NOTHING", //没有信息
    //关卡榜
    RANK_GUANQIA_UPDATE:"RANK_GUANQIA_UPDATE",

    //副本
    COPY_INFO_UPDATE: "COPY_INFO_UPDATE",  //副本信息更新
    COPY_ASK_CHALLENGE_RESULT: "COPY_ASK_CHALLENGE_RESULT",  //请求挑战副本的结果

    //投资
    INVEST_INFO_UPDATE:"INVEST_INFO_UPDATE", //投资信息更新

    //充值
    RECHARGE_INFO_UPDATE:"RECHARGE_INFO_UPDATE",//充值信息更新
    
    //转盘
    FORTUNE_VIEW_INFO_UPDATE:"FORTUNE_VIEW_INFO_UPDATE",//转盘数据更新
    FORTUNE_POOL_INFO_UPDATE:"FORTUNE_POOL_INFO_UPDATE",//转盘池数据更新
    FORTUNE_WHEEL_START:"FORTUNE_WHEEL_START",//转盘转动返回
    FORTUNE_WHEEL_STOP:"FORTUNE_WHEEL_STOP",//转盘转动返回
    
    
    //争霸
    HEGEMONY_INFO_UPDATE:"HEGEMONY_INFO_UPDATE", //争霸1界面信息更新
    HEGEMONY_MATCH_UPDATE:"HEGEMONY_MATCH_UPDATE",//匹配挑战信息
    HEGEMONY_REWARD_UPDATE:"HEGEMONY_REWARD_UPDATE",//争霸奖励信息更新
    
    

    //世界boss
    WORLDBOSS_INFO_UPDATE: "WORLDBOSS_INFO_UPDATE",   // 世界boss信息更新 
    WORLDBOSS_KILLRECORD_UPDATE: "WORLDBOSS_KILLRECORD_UPDATE",   //世界boss击杀记录更新
    WORLDBOSS_FIGHT: "WORLDBOSS_FIGHT",  //挑战世界boss中
    WORLDBOSS_CHEER: "WORLDBOSS_CHEER",  //挑战世界boss助威
    WORLDBOSS_CHEER_RESULT: "WORLDBOSS_CHEER_RESULT",  //助威结果
    WORLDBOSS_HURT_RANK_UPDATE: "WORLDBOSS_HURT_RANK_UPDATE",  //挑战boss时伤害排行更新

    //遭遇战
    ENCOUNTER_INFO_UPDATE: "ENCOUNTER_INFO_UPDATE",   //遭遇战信息更新
    ENCOUNTER_PK_REDUCE_SUCCESS:"ENCOUNTER_PK_REDUCE_SUCCESS",  //消除pk值成功
    ENCOUNTER_START_CHALLENGE_SUCCESS: "ENCOUNTER_START_CHALLENGE_SUCCESS",  //请求挑战成功

    //遭遇战
    ENCOUNTER_LOG_UPDATE:"ENCOUNTER_LOG_UPDATE",//遭遇战战斗记录

    //玩家战力变化
    PLAYER_COMBAT_UPDATE:"PLAYER_COMBAT_UPDATE",

    //查看玩家信息
    PLAYER_MSG_INQUIRE:"PLAYER_MSG_INQUIRE",
    PLAYER_HERO_ATTRIBUTE_INDEX_CHANGE:"PLAYER_HERO_ATTRIBUTE_INDEX_CHANGE",
    
    //战斗力显示飘字属性播放完成
    COMBAT_ATTR_FINISH:"COMBAT_ATTR_FINISH",
    //战斗力提升战斗力播放完成
    COMBAT_INCREASE_FINISH:"COMBAT_INCREASE_FINISH",
}
